sites:
  - name: Main Server
    description: This is a server.
    children:
      - name: Service 1
        description: This is a demo for p.mume.
        endpoint: "https://example.com"
      - name: Service 2
        description: This is a demo for p.mume.
        endpoint: "https://example.com"
      - name: Service 3
        description: This is a demo for p.mume.
        endpoint: "https://example.com"
  - name: Second Server
    description: This is a server, too.
    endpoint: "https://example.com"
    children:
      - name: Service
        description: This is a demo for p.mume.
        endpoint: "https://example.com"
