#:schema node_modules/wrangler/config-schema.json

name = "planter"
main = "src/workers/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
